### ISSUE TITLE
Update meta tags in the head element on language change

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/GoogleSheetCmsLight#6]
- [x] The following must be updated on language change.
- [x] The feature also check the meta tag are present in the document
- [x] The feature also check the meta tag are present in the source data.

Ex:
```html
    <title>Google Sheets CMS</title>
    <meta name="description" content="A library to load multilingal content from Google Sheet onto a website">

    <!-- To optimise the SEO using Open Graph protocol: https://ogp.me/, uncomment below -->
    <meta property="og:title" content="A website built with Gulp">
    <meta property="og:description" content="Enter your search criteria: Search    ">
    <meta property="og:url" content="index.html">
    <meta property="og:type" content="website">
    <meta property="og:image" content="img/android-chrome-192x192.png">
    <meta property="og:image:alt" content="A library to load multilingal content from Google Sheet onto a website">

    <!-- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@puzzlout">
    <meta name="twitter:creator" content="@LitzlerJeremie">
    <meta name="twitter:description" content="Enter your search criteria: Search    ">
    <meta name="twitter:image" content="https://gsheets-cms.netlify.app/img/android-chrome-192x192.png">
```
